#!/usr/bin/env python
import dotanotify
import time
import pynotify
import urllib2

if __name__ == '__main__':
    if not pynotify.init('dota-notify'):
        sys.exit(1)

    note = pynotify.Notification('', '')
    d = dotanotify.Dota()
    currentGames = []
    try:
        while True:
            try:
                games = d.live_league_games()
            except urllib2.URLError, e:
                print 'Dota network down at', time.asctime(), e

            for game in games['result']['games']:
                if game['lobby_id'] not in currentGames:
                    currentGames.append(game['lobby_id'])
                    message = '%s vs %s' % (game['dire_team']['team_name'],
                                                game['radiant_team']['team_name'])
                    title = 'Live Match:'
                    note.update(title, message, 'appointment-soon')
                    note.show()
            currentGames =  [g['lobby_id'] for g in games['result']['games']]
            time.sleep(30)
    finally:
        note.close()
